name: 'Hello World'
description: 'Greet someone'
inputs:
  private-ssh:
    description: 'private ssh key'
    required: true
    default: 'missing ssh key'
  key1:
    description: 'temp'
    required: true
    default: 'missing'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.key1 }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
